[package]
name = "rssg"
version = "0.1.0"
edition = "2021"

[dependencies]
pulldown-cmark = "0.11.0"
serde = "1.0.204"
serde_derive = "1.0.204"
tempdir = "0.3.7"
tera = "1.20.0"
yaml-front-matter = "0.1.0"
